give @s wsp:blaze_bow
give @s wsp:bogged_bow
give @s wsp:breeze_bow
give @s wsp:creaking_bow
give @s wsp:creeper_bow
give @s wsp:elder_guardian_bow
give @s wsp:ender_dragon_bow
give @s wsp:endermite_bow
give @s wsp:evoker_bow
give @s wsp:ghast_bow
give @s wsp:guardian_bow
give @s wsp:hoglin_bow
give @s wsp:husk_bow
give @s wsp:magma_bow
give @s wsp:parched_bow
give @s wsp:phantom_bow
give @s wsp:piglin_brute_bow
give @s wsp:pillager_bow
give @s wsp:ravager_bow
give @s wsp:shulker_bow
give @s wsp:silverfish_bow
give @s wsp:skeleton_bow
give @s wsp:slime_bow
give @s wsp:stray_bow
give @s wsp:sulfur_bow
give @s wsp:vex_bow
give @s wsp:vindicator_bow
give @s wsp:warden_bow
give @s wsp:witch_bow
give @s wsp:wither_bow
give @s wsp:wither_skeleton_bow
give @s wsp:zoglin_bow
give @s wsp:zombie_bow
give @s wsp:zombie_villager_bow