particle "minecraft:mob_portal" ~~0~
particle "minecraft:mob_portal" ~~0.1~
particle "minecraft:mob_portal" ~~0.2~
particle "minecraft:mob_portal" ~~0.3~
particle "minecraft:mob_portal" ~~0.4~
particle "minecraft:mob_portal" ~~0.5~
particle "minecraft:mob_portal" ~~0.6~
particle "minecraft:mob_portal" ~~0.7~
particle "minecraft:mob_portal" ~~0.8~
particle "minecraft:mob_portal" ~~0.9~
particle "minecraft:mob_portal" ~~1~
particle "minecraft:mob_portal" ~~0~
particle "minecraft:mob_portal" ~~0.1~
particle "minecraft:mob_portal" ~~0.1~
particle "minecraft:mob_portal" ~~0.1~
particle "minecraft:mob_portal" ~~0.2~
particle "minecraft:mob_portal" ~~0.3~
particle "minecraft:mob_portal" ~~0.4~
particle "minecraft:mob_portal" ~~0.5~
particle "minecraft:mob_portal" ~~0.6~
particle "minecraft:mob_portal" ~~0.7~
particle "minecraft:mob_portal" ~~0.8~
particle "minecraft:mob_portal" ~~0.9~
particle "minecraft:mob_portal" ~~1~